name: shadowed_carded_list
description: "A Flutter widget package providing a carded list with shadowed, scrollable content and small UI helpers."
version: 0.1.0
homepage: https://github.com/Rediflow-AI/Shadow_Carded_List
repository: https://github.com/Rediflow-AI/Shadow_Carded_List
issue_tracker: https://github.com/Rediflow-AI/Shadow_Carded_List/issues
documentation: https://github.com/Rediflow-AI/Shadow_Carded_List#readme
publish_to: "none" # Change to a valid server or remove before publishing

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Helpful metadata for pub.dev
flutter:
  uses-material-design: true

# Search keywords and categories used by pub.dev
keywords:
  - flutter
  - widget
  - list
  - card
  - shadow
categories:
  - flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
